### ISSUE TITLE
Linux

### ISSUE THREAD

**Issue by neuromancer** [dpjudas/UTEngine#1]
Hi,

Any plans for Linux support of this neat reimplementation?

Thanks!

**Comment by dpjudas** [comment]
Yes! That is the plan. :)

**Comment by JPLeBreton** [comment]
Just successfully compiled from Manjaro Linux. However I ran into the fact that the resource directory is hardcoded to "/home/mbn/UnrealTournament/Maps". I created a dir by that name with my UT content in it, and got this error when running UTEngine:
`Unhandled exception: Array properties not implemented`

**Comment by dpjudas** [comment]
You can change the path it uses by editing UTEngine/Engine.cpp. At the top of the file you'll find that path. Also, slightly further down you can control which map it will load, and slightly further down after that there's an #if 0 statement that can be changed to #if 1 to enable music playback.

Note that the code is currently only compatible with Unreal Tournament patch 436 - not 469. This is because they apparently made some changes to the scripts that now uses parts of the unrealscript VM I haven't implemented yet.

All of this will of course not be hardcoded in the long run. :)

**Comment by rohit-n** [comment]
Can confirm it works after I used the data files from GOG. Also compiled on Manjaro.

**Comment by sharkwouter** [comment]
It might be worth making a PR for adding instructions for how to build on Linux to the README or wiki.

**Comment by dpjudas** [comment]
ok I've updated the readme with build instructions and clarified this project is still work in progress. :)

**Comment by sharkwouter** [comment]
Oh nice, thanks!

**Comment by neuromancer** [comment]
Since there is already instruction on how to build in Linux, I will close this issue. Thanks a lot for the support. :smile:
